# Generated by Django 3.2.4 on 2021-07-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210701_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_id', models.CharField(default='', max_length=256, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(default='', max_length=256)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
