# Generated by Django 3.2.4 on 2021-07-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='moderator',
            field=models.CharField(default='test@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='group',
            name='topic',
            field=models.CharField(default='group call', max_length=100),
        ),
    ]
