# Generated by Django 3.2.4 on 2021-07-13 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210707_1750'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
