# Generated by Django 3.2.4 on 2021-07-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='user.Token'),
        ),
    ]
