# Generated by Django 3.2.4 on 2021-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210713_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='groups', to='user.Token'),
        ),
        migrations.AlterField(
            model_name='group',
            name='topic',
            field=models.CharField(default='new group', max_length=75),
        ),
    ]
